- module: nginx
  access:
    enabled: true
    var.paths:
      [
        "/Users/emmanueldemey/Documents/workspaces/oss/codelab-elastic/step0/nginxlogs/access.log*",
      ]
  error:
    enabled: true
    var.paths:
      [
        "/Users/emmanueldemey/Documents/workspaces/oss/codelab-elastic/step0/nginxlogs/error.log*",
      ]
