- module: nginx
  access:
    enabled: true
    var.paths: ["/Users/emmanueldemey/Documents/workspaces/oss/devoxx-universite-elastic/nginxlogs/access.log*"]
  error:
    enabled: true
    var.paths: ["/Users/emmanueldemey/Documents/workspaces/oss/devoxx-universite-elastic/nginxlogs/error.log*"]